DROP TABLE IF EXISTS `EVENT`;
DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER`
(
    `ID`        BIGINT       NOT NULL AUTO_INCREMENT  PRIMARY KEY,
    `NAME`      VARCHAR(10)  NOT NULL,
    `EMAIL`     VARCHAR(40)  NOT NULL,
    `PASSWORD`  VARCHAR(255) NOT NULL,
    `CREATEDAT` DATETIME     NOT NULL,
    `UPDATEDAT` DATETIME     NOT NULL
);

CREATE TABLE `EVENT`
(
    `ID`        BIGINT   NOT NULL AUTO_INCREMENT  PRIMARY KEY ,
    `USERID`    BIGINT   NOT NULL,
    `TITLE`     VARCHAR(255) NULL,
    `CONTEXTS`  TEXT NULL,
    `CREATEDAT` DATETIME NOT NULL,
    `UPDATEDAT` DATETIME NOT NULL,
    FOREIGN KEY (`USERID`) REFERENCES USER(ID)
);

commit;


